// frontend-react/src/presentation/components/NotificationBell.tsx
import { useState } from "react";
import { Bell } from "lucide-react";
import { useNotificationStore } from "../../application/notification/useNotificationStore";

export function NotificationBell() {
  const [open, setOpen] = useState(false);
  const notifications = useNotificationStore((state) => state.notifications);
  const unreadCount = useNotificationStore((state) => state.unreadCount);
  const markAllRead = useNotificationStore((state) => state.markAllRead);

  function toggle() {
    setOpen((prev) => {
      const next = !prev;
      if (next) markAllRead();
      return next;
    });
  }

  return (
    <div className="relative">
      <button
        onClick={toggle}
        className="relative p-2 rounded-lg hover:bg-neutral-100 transition-colors"
      >
        <Bell size={20} className="text-neutral-600" />
        {unreadCount > 0 && (
          <span className="absolute -top-0.5 -right-0.5 w-4 h-4 bg-danger-600 text-white text-[10px] font-bold rounded-full flex items-center justify-center">
            {unreadCount > 9 ? "9+" : unreadCount}
          </span>
        )}
      </button>

      {open && (
        <div className="absolute right-0 mt-2 w-72 bg-white rounded-lg shadow-lg border border-neutral-200 z-50 max-h-80 overflow-y-auto">
          <div className="px-4 py-3 border-b border-neutral-100">
            <p className="text-sm font-semibold text-neutral-700">
              Notifications
            </p>
          </div>

          {notifications.length === 0 ? (
            <p className="px-4 py-6 text-sm text-neutral-400 text-center">
              Aucune notification pour le moment.
            </p>
          ) : (
            <ul className="divide-y divide-neutral-100">
              {notifications.map((notification) => (
                <li key={notification.id} className="px-4 py-3">
                  <p className="text-sm text-neutral-700">
                    {notification.message}
                  </p>
                  <p className="text-xs text-neutral-400 mt-1">
                    {new Date(notification.receivedAt).toLocaleTimeString(
                      "fr-FR",
                      {
                        hour: "2-digit",
                        minute: "2-digit",
                      },
                    )}
                  </p>
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}

// frontend/src/app/shared/components/notification-bell/notification-bell.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IconComponent } from '../icon/icon.component';
import { NotificationService } from '../../../core/services/notification.service';

@Component({
  selector: 'app-notification-bell',
  standalone: true,
  imports: [CommonModule, IconComponent],
  templateUrl: './notification-bell.component.html',
})
export class NotificationBellComponent {
  open = signal(false);

  constructor(public notificationService: NotificationService) {}

  toggleOpen() {
    this.open.update((v) => !v);
    if (this.open()) {
      this.notificationService.markAllRead();
    }
  }
}

<div class="relative">
  <button
    (click)="toggleOpen()"
    class="relative p-2 rounded-lg hover:bg-neutral-100 transition-colors"
  >
    <app-icon name="bell" [size]="20" class="text-neutral-600"></app-icon>
    <span
      *ngIf="notificationService.unreadCount() > 0"
      class="absolute top-1 right-1 w-4 h-4 bg-danger-500 text-white text-xs rounded-full flex items-center justify-center font-bold"
    >
      {{ notificationService.unreadCount() }}
    </span>
  </button>

  <div
    *ngIf="open()"
    class="absolute right-0 top-10 w-72 bg-white border border-neutral-200 rounded-xl shadow-lg z-50 overflow-hidden"
  >
    <div class="px-4 py-3 border-b border-neutral-100 flex items-center justify-between">
      <p class="text-sm font-semibold text-neutral-800">Notifications</p>
      <button
        (click)="notificationService.clear()"
        class="text-xs text-neutral-400 hover:text-danger-500"
      >
        Tout effacer
      </button>
    </div>

    <div class="max-h-64 overflow-y-auto">
      <div *ngIf="notificationService.notifications().length === 0" class="text-center py-8">
        <app-icon name="bell" [size]="24" class="text-neutral-300 mx-auto mb-2"></app-icon>
        <p class="text-xs text-neutral-400">Aucune notification</p>
      </div>

      <div
        *ngFor="let notif of notificationService.notifications()"
        class="px-4 py-3 border-b border-neutral-50 hover:bg-neutral-50 transition-colors"
        [class.bg-primary-50]="!notif.read"
      >
        <p class="text-sm font-medium text-neutral-800">{{ notif.message }}</p>
        <p class="text-xs text-neutral-400 mt-0.5">{{ notif.type }}</p>
      </div>
    </div>
  </div>
</div>
