// frontend/src/app/layouts/etudiant-layout/etudiant-layout.component.ts
import { Component, signal } from '@angular/core';
import { Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../core/auth/auth.service';
import { IconComponent } from '../../shared/components/icon/icon.component';

@Component({
  selector: 'app-etudiant-layout',
  standalone: true,
  imports: [CommonModule, RouterOutlet, RouterLink, RouterLinkActive, IconComponent],
  templateUrl: './etudiant-layout.component.html',
})
export class EtudiantLayoutComponent {
  sidebarOpen = signal(true);

  navItems = [
    { label: 'Tableau de bord', route: '/etudiant/dashboard', icon: 'home' },
    { label: 'Mes notes', route: '/etudiant/notes', icon: 'clipboard-list' },
    { label: 'Mes relevés', route: '/etudiant/releves', icon: 'file-text' },
  ];

  constructor(
    public authService: AuthService,
    private router: Router,
  ) {}

  toggleSidebar() {
    this.sidebarOpen.update((v) => !v);
  }

  logout() {
    this.authService.logout();
  }

  getUserName() {
    const user = this.authService.currentUser();
    return user ? user.prenom + ' ' + user.nom : '';
  }
}

<div class="flex h-screen bg-neutral-50 overflow-hidden">
  <aside
    class="flex flex-col bg-white border-r border-neutral-200 transition-all duration-300"
    [class.w-64]="sidebarOpen()"
    [class.w-16]="!sidebarOpen()"
  >
    <div class="flex items-center gap-3 px-4 py-5 border-b border-neutral-100">
      <div class="w-8 h-8 bg-warning-500 rounded-lg flex items-center justify-center flex-shrink-0">
        <app-icon name="graduation-cap" [size]="18" class="text-white"></app-icon>
      </div>
      <span
        class="font-bold text-neutral-800 text-sm whitespace-nowrap overflow-hidden transition-all"
        [class.opacity-0]="!sidebarOpen()"
        [class.w-0]="!sidebarOpen()"
      >
        Espace Étudiant
      </span>
    </div>

    <nav class="flex-1 p-3 space-y-1">
      <a
        *ngFor="let item of navItems"
        [routerLink]="item.route"
        routerLinkActive="active"
        class="sidebar-link"
      >
        <app-icon [name]="item.icon" [size]="20"></app-icon>
        <span
          class="whitespace-nowrap overflow-hidden transition-all"
          [class.opacity-0]="!sidebarOpen()"
          [class.w-0]="!sidebarOpen()"
        >
          {{ item.label }}
        </span>
      </a>
    </nav>

    <div class="p-3 border-t border-neutral-100">
      <div class="flex items-center gap-3 px-3 py-2 rounded-lg bg-neutral-50">
        <div
          class="w-8 h-8 bg-warning-100 rounded-full flex items-center justify-center flex-shrink-0"
        >
          <app-icon name="user" [size]="16" class="text-warning-600"></app-icon>
        </div>
        <div
          class="overflow-hidden transition-all"
          [class.opacity-0]="!sidebarOpen()"
          [class.w-0]="!sidebarOpen()"
        >
          <p class="text-xs font-medium text-neutral-800 truncate">{{ getUserName() }}</p>
          <p class="text-xs text-neutral-400">Étudiant</p>
        </div>
      </div>
      <button
        (click)="logout()"
        class="sidebar-link w-full mt-1 text-danger-600 hover:bg-danger-50 hover:text-danger-700"
      >
        <app-icon name="log-out" [size]="20"></app-icon>
        <span
          class="whitespace-nowrap overflow-hidden transition-all"
          [class.opacity-0]="!sidebarOpen()"
          [class.w-0]="!sidebarOpen()"
        >
          Déconnexion
        </span>
      </button>
    </div>
  </aside>

  <div class="flex-1 flex flex-col overflow-hidden">
    <header class="bg-white border-b border-neutral-200 px-6 py-4 flex items-center gap-4">
      <button
        (click)="toggleSidebar()"
        class="p-2 rounded-lg hover:bg-neutral-100 transition-colors"
      >
        <app-icon name="menu" [size]="20" class="text-neutral-600"></app-icon>
      </button>
      <h1 class="text-lg font-semibold text-neutral-800 flex-1">Gestion des Notes</h1>
      <span class="badge badge-warning">Étudiant</span>
    </header>
    <main class="flex-1 overflow-y-auto p-6">
      <router-outlet />
    </main>
  </div>
</div>

// frontend-react/src/presentation/layouts/EtudiantLayout.tsx
import { useState } from "react";
import { NavLink, Outlet } from "react-router-dom";
import {
  LayoutDashboard,
  ClipboardList,
  FileText,
  GraduationCap,
  LogOut,
  Menu,
} from "lucide-react";
import { useAuth } from "../../application/auth/useAuth";
import { useLogout } from "../../application/auth/useLogout";
import { getNomComplet } from "../../domain/user";
import { NotificationBell } from "../components/NotificationBell";

const NAV_ITEMS = [
  {
    label: "Tableau de bord",
    to: "/etudiant/dashboard",
    icon: LayoutDashboard,
  },
  { label: "Mes notes", to: "/etudiant/notes", icon: ClipboardList },
  { label: "Mes relevés", to: "/etudiant/releves", icon: FileText },
];

export function EtudiantLayout() {
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const currentUser = useAuth((state) => state.currentUser);
  const logout = useLogout();

  return (
    <div className="flex h-screen bg-neutral-50 overflow-hidden">
      <aside
        className={`flex flex-col bg-white border-r border-neutral-200 transition-all duration-300 ${
          sidebarOpen ? "w-64" : "w-16"
        }`}
      >
        <div className="flex items-center gap-3 px-4 py-5 border-b border-neutral-100">
          <div className="w-8 h-8 bg-warning-500 rounded-lg flex items-center justify-center flex-shrink-0">
            <GraduationCap size={18} className="text-white" />
          </div>

          {sidebarOpen && (
            <span className="font-bold text-neutral-800 text-sm whitespace-nowrap">
              Espace Étudiant
            </span>
          )}
        </div>

        <nav className="flex-1 p-3 space-y-1">
          {NAV_ITEMS.map((item) => (
            <NavLink
              key={item.to}
              to={item.to}
              className={({ isActive }) =>
                `flex items-center gap-3 px-3 py-2 rounded-lg text-sm font-medium transition-colors ${
                  isActive
                    ? "bg-warning-50 text-warning-700"
                    : "text-neutral-600 hover:bg-neutral-100"
                }`
              }
            >
              <item.icon size={20} />
              {sidebarOpen && <span>{item.label}</span>}
            </NavLink>
          ))}
        </nav>

        <div className="p-3 border-t border-neutral-100">
          {sidebarOpen && currentUser && (
            <div className="flex items-center gap-3 px-3 py-2 rounded-lg bg-neutral-50 mb-1">
              <div className="w-8 h-8 bg-warning-100 rounded-full flex items-center justify-center flex-shrink-0">
                <span className="text-warning-600 text-xs font-bold">
                  {currentUser.prenom.charAt(0)}
                </span>
              </div>
              <div className="overflow-hidden">
                <p className="text-xs font-medium text-neutral-800 truncate">
                  {getNomComplet(currentUser)}
                </p>
                <p className="text-xs text-neutral-400">Étudiant</p>
              </div>
            </div>
          )}
          <button
            onClick={logout}
            className="flex items-center gap-3 px-3 py-2 rounded-lg text-sm font-medium w-full text-danger-600 hover:bg-danger-50 transition-colors"
          >
            <LogOut size={20} />
            {sidebarOpen && <span>Déconnexion</span>}
          </button>
        </div>
      </aside>

      <div className="flex-1 flex flex-col overflow-hidden">
        <header className="bg-white border-b border-neutral-200 px-6 py-4 flex items-center gap-4">
          <button
            onClick={() => setSidebarOpen((prev) => !prev)}
            className="p-2 rounded-lg hover:bg-neutral-100 transition-colors"
          >
            <Menu size={20} className="text-neutral-600" />
          </button>
          <h1 className="text-lg font-semibold text-neutral-800 flex-1">
            Gestion des Notes
          </h1>
          <NotificationBell />
          <span className="px-2.5 py-0.5 rounded-full text-xs font-medium bg-warning-50 text-warning-700">
            Étudiant
          </span>
        </header>

        <main className="flex-1 overflow-y-auto p-6">
          <Outlet />
        </main>
      </div>
    </div>
  );
}
